### ISSUE TITLE
Name of nowcast.conf

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#18] opened 2016-03-08 05:18 UTC
Here's a weird one...

This:

```
[nowcast]
model: vic
startdate: 2005-1-1
enddate: 2005-12-31
name: basin112
basin:  /media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/data/tests/basin.shp
resolution: 0.25

[vic]
precip: chirps
temperature: ncep
wind: ncep
save to: db
save: runoff
initialize: off
```

If given a new name like 'nowcasttest.conf' runs perfectly. But if I switch the name to 'nowcast.conf' I get this:

```
mrc@mrc-VPCZ114GX:/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/bin$ ./rheas nowcast.conf
Traceback (most recent call last):
  File "./rheas", line 17, in <module>
    sys.exit(rheas.run())
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/rheas.py", line 81, in run
    nowcast.execute(dbname, options)
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/nowcast.py", line 187, in execute
    runVIC(dbname, options)
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/nowcast.py", line 29, in runVIC
    runDeterministicVIC(dbname, options)
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/nowcast.py", line 76, in runDeterministicVIC
    model.writeForcings(prec, tmax, tmin, wind)
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/vic/vic.py", line 380, in writeForcings
    tmin) == len(self.lat) * ndays and len(wind) == len(self.lat) * ndays
AssertionError
```

It's fine now that I know, but I guess the system has a memory? An exception would be useful.

**Comment by AdamJDuncan** [comment] 2016-03-08 05:20
(ie I've run the nowcast.conf file on another basin before and now it won't accept that name... I've tried other variables, and it really is the name of the .conf file. Odd.)

**Comment by kandread** [comment] 2016-03-10 19:42
Not sure what the issue is. I just tried your config file and everything worked. Closing for now.

**Closed as completed by kandread** 2016-03-10 19:42 UTC
